parent=base

styles=dist/index.css
scripts=dist/index.js
favicons=img/favicon.ico==icon==image/x-icon img/favicon-16x16.png==icon==image/png==16x16 img/favicon-32x32.png==icon==image/png==32x32 img/apple-touch-icon.png==apple-touch-icon==image/png==180x180 img/android-chrome-192x192.png==icon==image/png==192x192 img/android-chrome-512x512.png==icon==image/png==512x512
